[project]
name = "NeuroRoute"
version = "1.0"
description = "AI-Driven High-Concurrency Network Packet Optimizer"
readme = "README.md"
requires-python = ">=3.9"
# Core dependencies required to run the application
dependencies = [
    "torch",
    "gymnasium",
    "pyzmq",
    "click",
    "rich",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# Development and testing tools
[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "ruff",
    "pre-commit",
]

# to tell python to only package the neuroroute dir and ignore configs
[tool.setuptools.packages.find]
include = ["neuroroute*"]

[tool.ruff]
line-length = 88
lint.extend-select=[]
lint.ignore=[]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
# Automatically handle async test functions since the project uses asyncio
asyncio_mode = "auto"
testpaths = ["tests"]
