"""
Benchmark and accuracy performance unit tests for optimized DQNAgent, TorchScript tracing,
batch decision interface, and pure NumPy fast path execution.
"""

import time
import numpy as np
import pytest
import torch

from neuroroute.ai.agent import DQNAgent, NumPyFastPath
from neuroroute.ai.optimizer import InferenceProfiler


def test_dqn_inference_latency():
    """
    Test that single-packet decision latencies are profiled accurately and microsecond scale.
    """
    state_dim = 11
    action_dim = 5
    agent = DQNAgent(state_dim=state_dim, action_dim=action_dim, epsilon=0.0)

    # JIT compile / trace model for zero-overhead inference
    agent.optimize_for_inference()
    assert agent.is_optimized is True
    assert agent.traced_policy_net is not None

    # Benchmark 1000 single inference decisions
    metrics = InferenceProfiler.profile_inference_latency(
        agent=agent, state_dim=state_dim, num_samples=1000, batch_size=32
    )

    assert "single_mean_us" in metrics
    assert "single_p95_us" in metrics
    assert "single_p99_us" in metrics
    assert "numpy_fastpath_mean_us" in metrics

    # Verify NumPy fastpath latency is microsecond scale (< 200 us on CPU)
    assert metrics["numpy_fastpath_mean_us"] < 200.0, (
        f"NumPy fastpath latency too high: {metrics['numpy_fastpath_mean_us']} us"
    )


def test_batch_inference_performance():
    """
    Test that vector batch inference (choose_action_batch) significantly improves decisions-per-second throughput.
    """
    state_dim = 11
    action_dim = 5
    agent = DQNAgent(state_dim=state_dim, action_dim=action_dim, epsilon=0.0)
    agent.optimize_for_inference()

    num_samples = 1000
    batch_size = 64
    states = np.random.randn(num_samples, state_dim).astype(np.float32)

    # 1. Sequential single decision timing
    t0_seq = time.perf_counter_ns()
    for i in range(num_samples):
        agent.choose_action(states[i])
    t1_seq = time.perf_counter_ns()
    duration_seq_us = (t1_seq - t0_seq) / 1000.0

    # 2. Vector batch decision timing
    num_batches = num_samples // batch_size
    batch_states = states[: num_batches * batch_size].reshape(num_batches, batch_size, state_dim)

    t0_batch = time.perf_counter_ns()
    for b in range(num_batches):
        agent.choose_action_batch(batch_states[b])
    t1_batch = time.perf_counter_ns()
    duration_batch_us = (t1_batch - t0_batch) / 1000.0

    # Assert batch processing is faster for total processed decisions
    assert duration_batch_us < duration_seq_us, (
        f"Batch time ({duration_batch_us} us) was not faster than sequential time ({duration_seq_us} us)"
    )


def test_optimized_policy_accuracy_consistency():
    """
    Test that Q-values generated by unoptimized policy_net, TorchScript traced model,
    and pure NumPy fast path are numerically identical within 1e-4 tolerance.
    """
    state_dim = 11
    action_dim = 5
    agent = DQNAgent(state_dim=state_dim, action_dim=action_dim)

    # Random test input states
    x = np.random.randn(10, state_dim).astype(np.float32)
    x_t = torch.from_numpy(x)

    # 1. Unoptimized policy_net forward pass
    agent.policy_net.eval()
    with torch.inference_mode():
        q_unoptimized = agent.policy_net(x_t).numpy()

    # 2. TorchScript traced model forward pass
    agent.optimize_for_inference(dummy_input=x_t[:1])
    with torch.inference_mode():
        q_traced = agent.traced_policy_net(x_t).numpy()

    # 3. Pure NumPy fast path forward pass
    fastpath = agent.export_to_numpy_fastpath()
    q_numpy = fastpath.predict_q_values(x)

    # Verify numerical consistency across all execution paths within 1e-4 tolerance
    np.testing.assert_allclose(q_unoptimized, q_traced, rtol=1e-4, atol=1e-4)
    np.testing.assert_allclose(q_unoptimized, q_numpy, rtol=1e-4, atol=1e-4)
